### ISSUE TITLE
Feature Request: Allow `range` to use variables for both start and stop

### ISSUE THREAD

**Issue by diego898** [EvanBalster/TiddlyWikiFormula#18]
Currently I can do:

```
[range<variable>]
```

but I cant do 

```
[range<start><stop>] 
```
for example. What I currently do to loop through an array is define a new variable with the size of the array - 1, and then within the list add 1 to the iterator variable.

**Comment by EvanBalster** [comment]
Hey, Diego —

Unfortunately the syntax you suggest would require changes to TiddlyWiki's filter operator parser, which is beyond the scope of formulas.  However, you can achieve what you want with a macro:

```
\define start_to_stop $(start)$,$(stop)$

...

<$vars start=101 stop=305>
<$list filter="[range<start_to_stop>]">
...
```

**Comment by diego898** [comment]
Thanks Evan I didnt know I could do that!
