### ISSUE TITLE
Formulas as Attributes 'Direct Syntax' broken in TW 5.1.17

### ISSUE THREAD

**Issue by joshuafontany** [EvanBalster/TiddlyWikiFormula#20]
Hi Evan,

I am using your excellent modloader plugin to patch the core for my complex-JSON support plugin I'm making. Super useful. I also tried Formulas to get/set data from nexted/complex JSON objects, and it works great.

I noticed after installing all your plugins that using formulas as direct-syntax Attributes, i.e.:
<svg
  width=(=10 * 10=)
  height=(=10 * 10=)
  viewBox="0 0 100 100">
<circle cx=50 cy=50 r=(=5 * 5=) />
</svg>

No longer works in TW 5.1.17 - I tested by dragging all 3 plugins to a fresh TW from the home site, and it also fails there (without any of my code/plugins/mods).

Thanks very much for this, cool stuff to show soon on the JSON end. Just wanted to bring this to your attention.

**Comment by EvanBalster** [comment]
Hey, Joshua —

Formulas as Attributes also requires the modloader plugin.  Do you have that installed?

**Comment by joshuafontany** [comment]
Yes. I am using it to patch the core wiki.js functions getDataItem and
setText, which works very well.

I did a test on tiddlywiki.com by dragging over all 3 plugins and trying
your svg demo, but it did not work until I changed mushroom brackets to the
<<formula >> macro (the same behaviour I saw in my wiki.

**Comment by joshuafontany** [comment]
Note for myself to re-check this in 5.1.19...

**Comment by joshuafontany** [comment]
Fixed in latest.
