### ISSUE TITLE
Attribute-Mod plugin causes fatal errors in TW5.1.19/20-prerelease

### ISSUE THREAD

**Issue by joshuafontany** [EvanBalster/TiddlyWikiFormula#21]
I've traced the first fatal error to the '*/parseutils.js' patch in the attribute-mod plugin. TW5 updated that core file and possibly others in the last 2 updates from *.17, and these are files affected by core patches from here. So code is replaced in the (now) wrong places. I will try to diff the affected tiddlers and recreate new patch files from new sources. Any other tips?

**Comment by EvanBalster** [comment]
Hey, Joshua —

Hmm, I figured the patch algorithm would be more robust than that, or would at least fail gracefully.  :(  The modloader is designed to cancel the entire mod if a patch fails.  Note that modloader does overwrite exactly one core JS shadow tiddler, so there could be a versioning issue there.

I'm very much Tied Up With Work for the next 5-10 days but I'd like to help look into this.

**Comment by joshuafontany** [comment]
Even,
Cool, sounds good. I'll keep poking around and see if I can reproduce it cleanly in a new wiki (not my plugin wiki that I imported into 5.1.20-pre), and catch any errors.

**Comment by joshuafontany** [comment]
Ok, well now I can only reproduce this in 5.1.20-pre, not 5.1.19. So it might just be instability or new updates that affect core components there. I'll roll back to 5.1.19 for my current projects. Thanks again!
