### ISSUE TITLE
patch/mod tiddler must be saved in UNIX style with line ending LF or  \n

### ISSUE THREAD

**Issue by CarpeDiemKopi** [EvanBalster/TiddlyWikiFormula#24]
Problem is, that in `diff_patch_match.js`

```
	diff_match_patch.prototype.patch_fromText = function (a) {
		var b = [];
		if (!a) return b;
		a = a.split("\n");
```
the tiddler text is dismantled by the pattern **`\n`**. 

The dismantling should be carried out in accordance with pattern **`\r\n|\n`**.

Either that or a hint at patch creation.

**Comment by joshuafontany** [comment]
The latest release today (for the TW5.1.23 release) fixes this by normalizing the patch and source text to both have the same line endings before passing them to the diff_match_patch library. Thanks for the bug report!
