### ISSUE TITLE
Add Time & Date processing

### ISSUE THREAD

**Issue by EvanBalster** [EvanBalster/TiddlyWikiFormula#5]
User TonyM requested some date processing facilities.  These are included in standard spreadsheet software, so they should probably be included here as well!

> I am really keen to use this as it seems to fill some serious gaps I have come across, in a very elegant way. An immediate Application I am interested in is adding Days or Months to Date Serial values.
> Imagine a Button that adds 7 days or 7 months to a Due date for example.
> However I am sure it is obvious the following parts of a Date Serial number need to increment differently, such as if +7 days moved into a new month (of length 28, 29, 30 and 31), or +7 months moves into a new year etc...
> I understand there are other tools to achieve this but the process is more convoluted. 
> I just wanted to point out this possible extension to see if there was some immediate "functions" that we could include or its just too deep a rabit hole to go Down?
> Perhaps a Date function that could increment/decrements a date serial number buy the specified units (Min, Hr, Day, Week, Month, year) and honour the calendar rules?
and if possible the ability to count the difference in specified units between two date serial numbers. Ideally allowing us to take the result and add it back to another date with the correct units.
> I imagine the libraries and source you are using may have such functions.
> Anyway, Do as you wish with this request, including ignoring it, if it is too much.

**Comment by HwWobbe** [comment]
As an interim, Quick & Dirty solution for date serial numbers, consider using julianDates ( https://en.wikipedia.org/wiki/Julian_day ).  It really makes the calendar arithmetic much simpler.  I've been using them as Tag values for quite some time and find them particularly useful as Prefix and Suffix operators since that provides a rough way to summarize the year into 37 tenDay time periods ( _00 ... _36 ).  Combined with Tobi''s cycleTags macro and a couple of Last & Next tiddlers, I've been content with this solution for several years.

That being said, I would appreciate a more precise and elegant solution of the type you are may be headed towards developing.

Thanks for your contributions,
Hans

**Comment by EvanBalster** [comment]
Currently my plan is to look into how TiddlyWiki already handles dates, and to try building on that.  (I'm not keen to set into the error-prone task of formatting date and time information by hand, and I'd rather not add new library dependencies to TW at this stage.)

**Comment by HwWobbe** [comment]
Thanks for the reply. 

I understand the desire to work within the TW and js library environments quite well.  I started using julianDates manually and promised myself I would automate that eventually.  Sadly, I've been distracted from back to doing so by other work.

I certainly look forward to your solution and hope to be able to migrate into it.

Cheers,
Hans

**Comment by EvanBalster** [comment]
Preliminary support added in 0.1.1:  https://evanbalster.com/tiddlywiki/formulas.html

Most of the meaty stuff is in this commit:  https://github.com/EvanBalster/TiddlyWikiFormula/commit/041176cc3f164587dfa7c1e4144b51c6b47eca0d

**Comment by EvanBalster** [comment]
User request:

> I have started using the date functions. What appears missing that I need at the moment is: Add_month, Add_year
> 
> In fact add_month would be sufficient because
> +12 months is add year
> +3 months is add quarter (next quarter)
> +6 months is next half year

This is a little tricky because months and years are variable quantities of time, but there's plenty of prior art (esp. in spreadsheet software).  I'll think about implementing this stuff (and I'm playing with it now).

In the meantime, it is possible to do stuff like this:

```c++
(= date(year(now()), month(now())+6, day(now())) =)
```

**Comment by EvanBalster** [comment]
We've reached a decent level of support with release 0.1.2:  evanbalster.com/tiddlywiki/formulas.html

  I suspect there are still functional gaps and bugs in the date implementation as it's all rather fussy.

**Comment by EvanBalster** [comment]
Added support for julian dates in 0.1.4.  At this point the functionality for dates (if not time-of-day) is relatively mature.

Future improvements could include timezone/UTC awareness.  Most dates currently use local time.
