### ISSUE TITLE
Rounding, ceiling and floor functions produce errors if second parameter provided

### ISSUE THREAD

**Issue by malgam** [EvanBalster/TiddlyWikiFormula#7]
When a second parameter (number of digits) is used for these functions an error is produced.  For example:

(= round(pi, 2) =)

Produces:

'ValueError: TypeError: value.asString is not a function value: 0'

They seem to work OK without the second parameter.

**Comment by EvanBalster** [comment]
Patched in https://github.com/EvanBalster/TiddlyWikiFormula/commit/0a8ff8f7b58ea86e4c2514ab45a6275fe34f0a92.  I'll put out a new release in a bit.

**Comment by EvanBalster** [comment]
Released 0.1.1, resolving this issue.
